spring:
  application:
    name: quote-service
  banner:
    location:
      classpath:banner.txt
  # Database
  datasource:
    url: jdbc:h2:/temp/test.db:QSDS
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
# REST

# General
application:
  version: 0.0.1-SNAPSHOT
